#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

export GOPATH=/Users/jprice/programs/gopath

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# echo "DEBUG1 $PATH"

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

# basic tmanpath setup
tmanpath=( $tmanpath /usr/local/opt/coreutils/libexec/gnuman )
tmanpath=( $tmanpath /usr/man /usr/local/man /usr/lang/man $HOME/man )
tmanpath=( $tmanpath /usr/openwin/man /usr/dt/man )
tmanpath=( $tmanpath /usr/X11R6/man )
tmanpath=( $tmanpath /usr/local/admin/man )
tmanpath=( $tmanpath /usr/share/man /usr/local/share/man )
tmanpath=( $tmanpath /opt/SUNWspro/man /opt/hpnp/man )
tmanpath=( $tmanpath /usr/opt/SUNWmd/man )
tmanpath=( $tmanpath /usr/openv/man /usr/openv/man/share/man )
tmanpath=( $tmanpath /usr/openv/netbackup/bin/goodies/man )
tmanpath=( $tmanpath /usr/local/home/build/jprice/xemacs/man )
tmanpath=( $tmanpath /Users/jprice/programs/git/homebrew/Cellar/lastpass-cli/1.0.0/share/man )

tpath=( ~/bin ~ )
tpath=( $tpath /Users/jprice/programs/git/homebrew/opt/go/libexec/bin )
tpath=( $tpath /Users/jprice/programs/git/homebrew/opt/coreutils/libexec/gnubin )
tpath=( $tpath /Users/jprice/programs/git/homebrew/bin )
tpath=( $tpath /Users/jprice/programs/git/iam-role-injector )
tpath=( $tpath /Applications/Docker.app/Contents/Resources/bin )
tpath=( $tpath $GOPATH/bin )
tpath=( $tpath /usr/local/opt/coreutils/libexec/gnubin )
tpath=( $tpath /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin )
tpath=( $tpath /etc /usr/etc /opt/etc /usr/local/etc )
tpath=( $tpath /usr/local/home/build/jprice/xemacs/bin )
tpath=( $tpath /usr/local/go/bin )
tpath=( $tpath /usr/ucb )
tpath=( $tpath /usr/games )
tpath=( $tpath /opt/gnome/bin /opt/gnome/sbin )
tpath=( $tpath /usr/sbin/nsr /usr/bin/nsr )
tpath=( $tpath /usr/local/admin/bin /usr/local/admin/sbin )

typeset -U path
path=()
for dir in $tpath ; do
   [[ -d $dir ]] && path=($path $dir)
done
unset tpath

typeset -U manpath
manpath=()
for dir in $tmanpath ; do
   [[ -d $dir ]] && manpath=($manpath $dir)
done
unset tmanpath

export path manpath PATH MANPATH

# echo "DEBUG2 $PATH"
#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

if [[ $(uname) == "Darwin" ]]; then
    alias top='top -u'
fi
